### ISSUE TITLE
It seems to have been broken since 3.11 on M1 Mac

### ISSUE THREAD

**Issue by ipiiia** [TeamFelnull/IamMusicPlayer#26]
[23:43:52] [Music Loader Thread: Ct6BUPvE2sM/ERROR]: Failed to load music: Ct6BUPvE2sM
java.lang.IllegalStateException: Load failed
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2) ~[?:?]
	at dev.felnull.imp.client.music.MusicLoadThread.run(MusicLoadThread.java:64) [iammusicplayer-fabric-1.18.2-3.12.jar:?]
[23:43:59] [Music Loader Thread: Ct6BUPvE2sM/ERROR]: Failed to load music: Ct6BUPvE2sM
java.lang.IllegalStateException: Load failed
	at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.2) ~[?:?]
	at dev.felnull.imp.client.music.MusicLoadThread.run(MusicLoadThread.java:64) [iammusicplayer-fabric-1.18.2-3.12.jar:?]

music will not play with the error.

3.10 still works fine

**Comment by MORIMORI0317** [comment]
The cause was that the download URL of the native library was specified incorrectly.
Fixed URL, no need to update IMP.
Try launching IMP 1.11 or later again
