### ISSUE TITLE
Patchouli failed to load manual

### ISSUE THREAD

**Issue by moderninity** [TeamFelnull/IamMusicPlayer#68]
does this help you guys out? Fabric 1.20.1 version IamMusicPlayer-1.20-3.22.0-alpha.2-Fabric
Awesome mod! 

```
[19:37:39] [Render thread/ERROR]: Failed to load book iammusicplayer:manual defined by mod iammusicplayer, skipping
--
1124 | java.lang.IllegalArgumentException: Book iammusicplayer:manual has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
1125 | at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
1126 | at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
1127 | at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
1128 | at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
1129 | at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
1130 | at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[Patchouli-1.20.1-81-FABRIC.jar:?]
1131 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.22.jar:?]
1132 | at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.22.jar:?]
1133 | at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) ~[fabric-loader-0.14.22.jar:?]
1134 | at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458) ~[client-intermediary.jar:?]
1135 | at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1-0.14.22.jar:?]
1136 | at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
1137 | at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
1138 | at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
```

full log if you need it: https://mclo.gs/MWiZBco

**Comment by iaddda** [comment]
I'm having the same issue. Does the team still care about issues?

**Comment by tt-thoma** [comment]
Can confirm (Fabric 1.20.1)
```
[Render thread/ERROR] (patchouli) Failed to load book iammusicplayer:manual defined by mod iammusicplayer, skipping
java.lang.IllegalArgumentException: Book iammusicplayer:manual has use_resource_pack set to false. This behaviour was removed in 1.20. The book author should enable this flag and move all book contents clientside to /assets/, leaving the book.json in /data/. See https://vazkiimods.github.io/Patchouli/docs/upgrading/upgrade-guide-120 for details.
at vazkii.patchouli.common.book.Book.<init>(Book.java:145) ~[Patchouli-1.20.1-84.1-FABRIC.jar:?]
at vazkii.patchouli.common.book.BookRegistry.loadBook(BookRegistry.java:90) ~[Patchouli-1.20.1-84.1-FABRIC.jar:?]
at vazkii.patchouli.common.book.BookRegistry.lambda$init$3(BookRegistry.java:75) ~[Patchouli-1.20.1-84.1-FABRIC.jar:?]
at java.util.HashMap.forEach(Unknown Source) ~[?:?]
at vazkii.patchouli.common.book.BookRegistry.init(BookRegistry.java:70) ~[Patchouli-1.20.1-84.1-FABRIC.jar:?]
at vazkii.patchouli.fabric.common.FabricModInitializer.onInitialize(FabricModInitializer.java:33) ~[Patchouli-1.20.1-84.1-FABRIC.jar:?]
at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.14.jar:?]
at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52) ~[fabric-loader-0.16.14.jar:?]
at net.minecraft.class_310.<init>(class_310.java:458) ~[client-intermediary.jar:?]
at net.minecraft.client.main.Main.main(Main.java:211) ~[1.20.1-0.16.14.jar:?]
at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) ~[fabric-loader-0.16.14.jar:?]
at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.16.14.jar:?]
at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.16.14.jar:?]
```
