### ISSUE TITLE
No audio in Minecraft 1.20.1 with YouTube

### ISSUE THREAD

**Issue by XDJLionZ265X** [TeamFelNull/IamMusicPlayer#86]
Hi, I'm trying the mod on Minecraft 1.20.1 and it seems that there is a bug where the music loaded from YouTube doesn't play, but the music from Sound Cloud does. Please could you check it?

**Comment by BlackDragonCZ** [comment]
I have same proble, youtube keep changing algorithm to play videos elsewhere than on youtube itself, this means Autor of our mod need to constantly updating code to make it work again :(

**Comment by milkybat** [comment]
I'm also having this issue. It seems manually uploading music isn't working for me too.

**Comment by VirtualGaming1** [comment]
I am having the same issue as well and here is the error code it is sending to the log

> [09:41:49] [lava-daemon-pool-playback-184-thread-1/ERROR]:Audio track error: WsDyRAPFBC8dev.felnull.imp.include.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Please sign in
> 	at dev.felnull.imp.include.dev.lavalink.youtube.clients.skeleton.Client.getPlayabilityStatus(Client.java:73) ~[iammusicplayer-forge-mc1.20-3.22.0-alpha.5.jar%23493!/:?]
> 	at dev.felnull.imp.include.dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:98) ~[iammusicplayer-forge-mc1.20-3.22.0-alpha.5.jar%23493!/:?]
> 	at dev.felnull.imp.include.dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35) ~[iammusicplayer-forge-mc1.20-3.22.0-alpha.5.jar%23493!/:?]
> 	at dev.felnull.imp.include.dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:183) ~[iammusicplayer-forge-mc1.20-3.22.0-alpha.5.jar%23493!/:?]
> 	at dev.felnull.imp.include.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:109) ~[iammusicplayer-forge-mc1.20-3.22.0-alpha.5.jar%23493!/:?]
> 	at dev.felnull.imp.include.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71) ~[iammusicplayer-forge-mc1.20-3.22.0-alpha.5.jar%23493!/:?]
> 	at dev.felnull.imp.include.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[iammusicplayer-forge-mc1.20-3.22.0-alpha.5.jar%23493!/:?]
> 	at dev.felnull.imp.include.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:330) ~[iammusicplayer-forge-mc1.20-3.22.0-alpha.5.jar%23493!/:?]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
> 	at java.lang.Thread.run(Unknown Source) ~[?:?]
